version: "3.7"

services:
    db:
        build:
            dockerfile: Dockerfile-pg
            context: .
            args:
                SQL_FILE: multidatabase.sh
        environment:
            - POSTGRES_USER=authentic8
            - POSTGRES_DB=authentic8
            - POSTGRES_PASSWORD=authentic8
            - POSTGRES_MULTIPLE_DATABASES=authentic8_csrfs,authentic8_passreset,authentic8_session

    app:
        image: golang
        volumes:
            - ./:/go/src/authentic8/
        command: go test ./... -covermode=atomic -coverprofile=coverage.txt -race
        working_dir: /go/src/authentic8
        environment:
            WAIT_HOSTS: db:5432
            WAIT_BEFORE_HOSTS: 5
