version: "3.7"

services:
    db:
        build:
            dockerfile: Dockerfile-pg
            context: .
            args:
                SQL_FILE: multidatabase.sh
        environment:
            - POSTGRES_USER=authentic
            - POSTGRES_DB=authentic
            - POSTGRES_PASSWORD=authentic
            - POSTGRES_MULTIPLE_DATABASES=authentic_csrfs,authentic_passreset,authentic_session

    app:
        image: golang
        volumes:
            - ./:/go/src/authentic/
        command: go test ./... -covermode=atomic -coverprofile=coverage.txt -race
        working_dir: /go/src/authentic
        environment:
            WAIT_HOSTS: db:5432
            WAIT_BEFORE_HOSTS: 5
